### ISSUE TITLE
output image are not generated

### ISSUE THREAD

**Issue by jodyngo** [Mugichoko445/Fast-Digital-Image-Inpainting#1]
I tried to run demo (using your example image), but no output generated. May you please advise this issue?

**Comment by Mugichoko445** [comment]
Sorry that I didn't notice your comment for a while.
The reason is just simply because the output image is just displayed and is not wrote on your storage. I modified "Main.cpp" to output the inpainted result on the local storage. After running the code, please check the "data" folder. You'll find the results, "inpaint.png."
See: https://github.com/Mugichoko445/Fast-Digital-Image-Inpainting/commit/3bbb392eec22dc7f7ec33c82a78ae7e81f80621c
