### ISSUE TITLE
Is is good for real time inpainting?

### ISSUE THREAD

**Issue by JeyP4** [Mugichoko445/Fast-Digital-Image-Inpainting#3]
As I am looking for very fast inpainting.
Do you think it is faster than`cv.inpaint(img,mask,3,cv.INPAINT_TELEA)`?

**Comment by Mugichoko445** [comment]
Hi, sorry for my late response. I've not checked this repo. for a long time.
It's hard to tell which one is faster, since it depends on the size of the image, the number of pixels to be inpainted, your CPU architecture, etc. However, you can simply test and compare this implementation and cv::inpaint.
